### ISSUE TITLE
第131回 こんちゃん、けん、ちなつ

### ISSUE THREAD

**Issue by ckanayama** [yochiyochirb/meetups#1415]

**Comment by ken3ypa** [comment]
よろしくおねがいします！

**Comment by konchanxxx** [comment]
オネシャス:smile:

**Comment by ckanayama** [comment]
お願いします!!

**Comment by ken3ypa** [comment]
>小さな変更のためにわざわざブランチを作成する必要はありませんが、

どれぐらい小さいのだと切らないってこと？
粒度に困る

**Comment by ckanayama** [comment]
良い習慣

**Comment by ckanayama** [comment]
良い師匠を見つけること

**Comment by ken3ypa** [comment]
(1)良い師匠を見つける
・開発に対する姿勢
　・責任持って作りきる
　・レビューの細かさ
　・ユーザへの責任を感じつつ、妥協しない

**Comment by ckanayama** [comment]
まとめて作業してしまってから
変更のまとまりをコミットする

**Comment by ken3ypa** [comment]
-a　はあんまり使わないかも？ byこんちゃん
一度ガッと作って、変更のまとまりをコミットしていく

**Comment by ckanayama** [comment]
>コミットメッセージは現在形かつ命令形で書く

**Comment by ken3ypa** [comment]
日本語だと体言止め

**Comment by ken3ypa** [comment]
>Box 4. Committing to Git
By design, Git requires every commit to include a commit message describing the purpose of the commit. Typically, this takes the form of a single line, usually limited to around 72 characters, with an optional longer message if desired (Section 4.2.3). Although conventions for commit messages vary (Figure 5),8 the style adopted in this tutorial is to write commit messages in the present tense using the imperative mood, as in “Initialize repository” rather than “Initializes repository” or “Initialized repository”. The reason for this convention is that Git models commits as a series of text transformations, and in this context it makes sense to describe what each commit does instead of what it did. Moreover, this usage agrees with the convention followed by the commit messages generated by Git commands themselves (e.g., “merge” rather than “merges” or “merged”). For more information, see the GitHub article “Shiny new commit styles”.

Committing to Git
https://www.learnenough.com/git-tutorial#aside-commit_messages

にちゃんと書いてるんすね。読み飛ばしてました

**Comment by ckanayama** [comment]
さっきの記事です。
Githubの中の人に聞いた、commit識別番号を人間でも扱いやすくする3つの工夫
http://naoyashiga.hatenablog.com/entry/2013/11/22/013406

**Comment by konchanxxx** [comment]
commit hash のunique性をどうやって担保している???

**Comment by ken3ypa** [comment]
Gitのコミットハッシュ値は、どうやって同値性を保っているの？
> 9e47c22　こういうやつ

■まず作り方
https://tech.mercari.com/entry/2016/02/08/173000
https://qiita.com/suzuki_koya/items/ec253845f2b07b9c45c0

tree, parent, author, commiterとファイルのbyte数をsha1でハッシュ化して生成する

■被ったらどうなるの？
・先にコミットした人のものが優先される
・かぶる可能性は天文学的数字(でもかぶる可能性は微レ存)

**Comment by konchanxxx** [comment]
https://tech.mercari.com/entry/2016/02/08/173000

**Comment by konchanxxx** [comment]
1方向ハッシュ関数 sha1
https://qiita.com/jackpod/items/84cf1b741c4975bbedca

**Comment by konchanxxx** [comment]
> トピックブランチの削除は必須ではありません。実際、トピックブランチを削除せずにそのままにしておくことはよく行われています。トピックブランチを削除せずに残しておけば、トピックブランチとmasterブランチを交互に行き来して、キリの良い所で変更をマージする事ができます。

トピックブランチを使いまわす??

**Comment by konchanxxx** [comment]
エピックブランチ、トピックブランチ、フィーチャーブランチ??呼び方色々ブランチ達

**Comment by ken3ypa** [comment]
development　ではsqlite
production　　ではpostgreSQL　使う

>HerokuではSQLiteがサポートされていないため

駄目なきがする。。。 byこんちゃん

**Comment by konchanxxx** [comment]
本番環境と開発環境でDB別にするのはよろしくない気がす

**Comment by ckanayama** [comment]
1.5.1 Herokuのセットアップ 読了

**Comment by ken3ypa** [comment]
>Heroku、名前を指定しないと謎の名前になりますよね　by　ちなつ

afternoon-waveという中2病感溢れる名前ができました笑

**Comment by konchanxxx** [comment]
永和二中に入れる＾＾ニッコリ

**Comment by konchanxxx** [comment]
`アプレンティスシップパターン`

https://www.amazon.co.jp/%E3%82%A2%E3%83%97%E3%83%AC%E3%83%B3%E3%83%86%E3%82%A3%E3%82%B9%E3%82%B7%E3%83%83%E3%83%97%E3%83%BB%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3-%E2%80%95%E5%BE%92%E5%BC%9F%E5%88%B6%E5%BA%A6%E3%81%AB%E5%AD%A6%E3%81%B6%E7%86%9F%E7%B7%B4%E6%8A%80%E8%A1%93%E8%80%85%E3%81%AE%E6%8A%80%E3%81%A8%E5%BF%83%E5%BE%97-THEORY-PRACTICE-Dave-Hoover/dp/4873114608

**Comment by ken3ypa** [comment]
情熱プログラマとアプレンティスシップパターンは
読むとモチベ爆上げ
読むレッドブル

**Comment by konchanxxx** [comment]
`情熱プログラマ`

https://www.amazon.co.jp/dp/B01IGW5MQ0/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1

**Comment by ckanayama** [comment]
[『SOFT SKILLS　ソフトウェア開発者の人生マニュアル』](https://www.amazon.co.jp/SOFT-SKILLS-%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E9%96%8B%E7%99%BA%E8%80%85%E3%81%AE%E4%BA%BA%E7%94%9F%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB-%E3%82%B8%E3%83%A7%E3%83%B3%E3%83%BB%E3%82%BD%E3%83%B3%E3%83%A1%E3%82%BA-ebook/dp/B01GDS0994/)
